name: amonitor
description: AMonitor

version: 3.1.208+208

environment:
  sdk: ">=3.5.0 <4.0.0"

publish_to: none

dependencies:
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.4+5
  get_it: ^7.7.0
  hive: ^2.2.3
  mobx: ^2.2.0+1
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  workmanager: ^0.5.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  intl_utils: ^2.8.2
  mobx_codegen: ^2.2.0+1
  test: ^1.25.2

flutter_launcher_icons:
  ios: true
  android: true
  image_path: scripts/ios_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/

flutter_intl:
  main_locale: en
  enabled: true
  arb_dir: lib/L3_app/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/L3_app/l10n/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated

# https://pub.dev/packages/flutter_native_splash:
# dart run flutter_native_splash:create
# Исходная картинка должна быть @4x
# после запуска команды вручную заменить все измененные изображения, т.к. очень плохо ресайзит, размер больших больше, а мелкие - лесенкой все
flutter_native_splash:
  image: "assets/images/background.png"
